import fs from 'fs';
import path from 'path';

const indexPath = path.resolve('index.html');
let html = fs.readFileSync(indexPath, 'utf8');

const newPrayersSnippet = `                { id: "p_15", title: "Oração da Noite (Exame de Consciência)", category: "Dia a dia", text: "Senhor, ao terminar este dia, venho à vossa presença.\\n\\n1. Ação de graças: Revejo o dia e agradeço pelos dons recebidos — a vida, os encontros, o pão, o trabalho.\\n\\n2. Luz do Espírito: Peço ao Espírito Santo que ilumine minha memória e meu coração.\\n\\n3. Revisão do dia: Onde estive hoje? O que fiz? Como amei? Onde faltei com o amor a Deus e ao próximo?\\n\\n4. Arrependimento: Peço perdão pelas faltas cometidas, pelas omissões do bem e pelas palavras que feriram.\\n\\n5. Propósito: Confio o amanhã à vossa providência e proponho amar melhor.\\n\\nGuardai-me nesta noite, Senhor, sob as vossas asas.\\nAmém." },
                {
                    id: "p_16",
                    title: "Via-Sacra (As 14 Estações da Paixão do Senhor)",
                    category: "Grandes Devoções",
                    text: "ORAÇÃO INICIAL:\\nSenhor Jesus, nós nos unimos à Vossa dolorosa Paixão e Morte de Cruz, pela redenção da humanidade.\\n\\n(Em cada estação reza-se: 'Nós Vos adoramos, ó Cristo, e Vos bendizemos, porque pela Vossa Santa Cruz remistes o mundo.')\\n\\n1ª Estação: Jesus é condenado à morte.\\nPilatos lava as mãos; o Inocente abraça a sentença para nos livrar da morte eterna.\\n\\n2ª Estação: Jesus carrega a Cruz aos ombros.\\nO Salvador recebe sobre os ombros feridos o peso de todas as nossas culpas.\\n\\n3ª Estação: Jesus cai pela primeira vez.\\nSob o peso do madeiro, o Filho de Deus beija a terra para reerguer os pecadores.\\n\\n4ª Estação: Jesus encontra sua Mãe Santíssima.\\nO olhar doloroso de Maria e de Jesus une dois corações no mesmo sacrifício redentor.\\n\\n5ª Estação: Simão Cirineu ajuda Jesus a levar a Cruz.\\nSomos chamados a carregar a cruz uns dos outros na caridade fraterna.\\n\\n6ª Estação: Verônica enxuga o rosto de Jesus.\\nUm gesto de compaixão grava para sempre a Sagrada Face no linho da caridade.\\n\\n7ª Estação: Jesus cai pela segunda vez.\\nAumentam as dores físicas; cresce o amor infinito do Redentor pelos homens.\\n\\n8ª Estação: Jesus consola as mulheres de Jerusalém.\\n'Não choreis por Mim, mas por vós mesmas e por vossos filhos'.\\n\\n9ª Estação: Jesus cai pela terceira vez.\\nQuase sem forças, o Senhor atinge o cume do Calvário para nossa justificação.\\n\\n10ª Estação: Jesus é despojado de suas vestes.\\nPartilham Suas túnicas; Jesus ensina o desapego e a pureza de coração.\\n\\n11ª Estação: Jesus é pregado na Cruz.\\nCravos transpassam as mãos e os pés do Autor da Vida: 'Pai, perdoa-lhes, não sabem o que fazem'.\\n\\n12ª Estação: Jesus morre na Cruz.\\n'Tudo está consumado'. O véu do templo se rasga; Jesus entrega o Seu Espírito.\\n\\n13ª Estação: Jesus é descido da Cruz e entregue a Sua Mãe.\\nNos braços da Piedade repousa o Cordeiro imolado por nosso amor.\\n\\n14ª Estação: Jesus é sepultado.\\nNa esperança certa da Ressurreição pascal, a morte é vencida para sempre.\\n\\nORAÇÃO FINAL:\\nSenhor Jesus Cristo, que pela Vossa Santa Cruz nos alcançastes a salvação eterna, concedei-nos a graça de Vos seguir com amor até a glória da Ressurreição. Amém."
                },
                {
                    id: "p_17",
                    title: "Ofício da Imaculada Conceição",
                    category: "Maria",
                    text: "MATINAS:\\nAbri, lábios meus, para bendizer a Virgem Maria.\\nDeus vos salve, Maria, Senhora do mundo, Rainha dos céus e das virgens.\\nEstrela da manhã, cheia de graça divina, socorrei a nós e ao mundo.\\n\\nPRIMA:\\nDeus vos salve, templo consagrado à Trindade Santa.\\nTu fostes preservada da culpa original desde o primeiro instante de tua conceição pura.\\nRogai por nós, Mãe de misericórdia.\\n\\nTERÇA:\\nDeus vos salve, Arca da Aliança e trono do verdadeiro Salomão.\\nO Altíssimo vos adornou com todas as virtudes para serdes Mãe digna do Salvador.\\n\\nSEXTA:\\nDeus vos salve, Virgem Mãe, Cidade de refúgio e porta do Céu.\\nEm vós resplandece a beleza do Criador que esmagou a cabeça da serpente antiga.\\n\\nNOA:\\nDeus vos salve, Cidade de Deus e monte sagrado.\\nSocorrei os pecadores, curai os enfermos e guiai os navegantes neste mar revolto.\\n\\nVÉSPERAS:\\nDeus vos salve, Luz que não conhece ocaso, Mãe do Sol de Justiça.\\nA vós recorremos nas horas de tentação e tribulação terrena.\\n\\nCOMPLETAS:\\nRogai por nós, Virgem Imaculada, para que sejamos dignos das promessas de Cristo.\\nGuardai o nosso sono, purificai a nossa alma e conduzi-nos à eterna bem-aventurança.\\n\\nORAÇÃO:\\nSanta Maria, Rainha dos céus, Mãe de Nosso Senhor Jesus Cristo e Senhora do mundo, que a nenhum pecador desamparais nem desprezais: ponde em nós os olhos de vossa piedade e alcançai-nos o perdão de todos os nossos pecados. Por Cristo, Nosso Senhor. Amém."
                },
                {
                    id: "p_18",
                    title: "Angelus Domini (O Anjo do Senhor)",
                    category: "Maria",
                    text: "V. O Anjo do Senhor anunciou a Maria.\\nR. E Ela concebeu do Espírito Santo.\\nAve-Maria...\\n\\nV. Eis aqui a serva do Senhor.\\nR. Faça-se em mim segundo a Vossa palavra.\\nAve-Maria...\\n\\nV. E o Verbo se fez carne (inclina-se a cabeça).\\nR. E habitou entre nós.\\nAve-Maria...\\n\\nV. Rogai por nós, Santa Mãe de Deus.\\nR. Para que sejamos dignos das promessas de Cristo.\\n\\nOREMOS:\\nInfundi, Senhor, a Vossa graça em nossas almas, para que nós, que pela anunciação do Anjo conhecemos a encarnação de Jesus Cristo, Vosso Filho, cheguemos, por Sua Paixão e Morte na Cruz, à glória da Ressurreição. Por Cristo, Nosso Senhor. Amém.\\n\\nGlória ao Pai... (3 vezes)"
                },
                {
                    id: "p_19",
                    title: "Regina Caeli (Rainha do Céu — Tempo Pascal)",
                    category: "Maria",
                    text: "(Reza-se no lugar do Angelus durante o Tempo Pascal, da Páscoa ao Domingo de Pentecostes)\\n\\nV. Rainha do Céu, alegrai-vos, aleluia!\\nR. Porque Aquele que merecestes trazer em vosso seio, aleluia!\\n\\nV. Ressuscitou como havia dito, aleluia!\\nR. Rogai por nós a Deus, aleluia!\\n\\nV. Alegrai-vos e exultai, ó Virgem Maria, aleluia!\\nR. Porque o Senhor ressuscitou verdadeiramente, aleluia!\\n\\nOREMOS:\\nÓ Deus, que Vos dignastes alegrar o mundo com a Ressurreição do Vosso Filho, Nosso Senhor Jesus Cristo, concedei-nos, nós Vos suplicamos, que por Sua Mãe, a Virgem Maria, alcancemos as alegrias da vida eterna. Por Cristo, Nosso Senhor. Amém."
                },
                {
                    id: "p_20",
                    title: "Ladainha Lauretana (Ladainha de Nossa Senhora)",
                    category: "Ladainhas",
                    text: "Senhor, tende piedade de nós.\\nCristo, tende piedade de nós.\\nSenhor, tende piedade de nós.\\nCristo, ouvi-nos.\\nCristo, atendei-nos.\\n\\nDeus Pai dos céus, tende piedade de nós.\\nDeus Filho, Redentor do mundo, tende piedade de nós.\\nDeus Espírito Santo, tende piedade de nós.\\nSantíssima Trindade, que sois um só Deus, tende piedade de nós.\\n\\nSanta Maria, rogai por nós.\\nSanta Mãe de Deus, rogai por nós.\\nSanta Virgem das virgens, rogai por nós.\\nMãe de Cristo, rogai por nós.\\nMãe da Igreja, rogai por nós.\\nMãe de misericórdia, rogai por nós.\\nMãe da divina graça, rogai por nós.\\nMãe da esperança, rogai por nós.\\nMãe puríssima, rogai por nós.\\nMãe castíssima, rogai por nós.\\nMãe sempre virgem, rogai por nós.\\nMãe imaculada, rogai por nós.\\nMãe amável, rogai por nós.\\nMãe admirável, rogai por nós.\\nMãe do bom conselho, rogai por nós.\\nMãe do Criador, rogai por nós.\\nMãe do Salvador, rogai por nós.\\nVirgem prudentíssima, rogai por nós.\\nVirgem venerável, rogai por nós.\\nVirgem louvável, rogai por nós.\\nVirgem poderosa, rogai por nós.\\nVirgem clemente, rogai por nós.\\nVirgem fiel, rogai por nós.\\nEspelho de justiça, rogai por nós.\\nSede da sabedoria, rogai por nós.\\nCausa de nossa alegria, rogai por nós.\\nVaso espiritual, rogai por nós.\\nVaso honorífico, rogai por nós.\\nVaso insigne de devoção, rogai por nós.\\nRosa mística, rogai por nós.\\nTorre de Davi, rogai por nós.\\nTorre de marfim, rogai por nós.\\nCasa de ouro, rogai por nós.\\nArca da aliança, rogai por nós.\\nPorta do céu, rogai por nós.\\nEstrela da manhã, rogai por nós.\\nSaúde dos enfermos, rogai por nós.\\nRefúgio dos pecadores, rogai por nós.\\nSocorro dos migrantes, rogai por nós.\\nConsoladora dos aflitos, rogai por nós.\\nAuxílio dos cristãos, rogai por nós.\\nRainha dos Anjos, rogai por nós.\\nRainha dos Patriarcas, rogai por nós.\\nRainha dos Profetas, rogai por nós.\\nRainha dos Apóstolos, rogai por nós.\\nRainha dos Mártires, rogai por nós.\\nRainha dos Confessores, rogai por nós.\\nRainha das Virgens, rogai por nós.\\nRainha de todos os Santos, rogai por nós.\\nRainha concebida sem pecado original, rogai por nós.\\nRainha assunta aos céus, rogai por nós.\\nRainha do Santo Rosário, rogai por nós.\\nRainha da família, rogai por nós.\\nRainha da paz, rogai por nós.\\n\\nCordeiro de Deus, que tirais os pecados do mundo, perdoai-nos, Senhor.\\nCordeiro de Deus, que tirais os pecados do mundo, ouvi-nos, Senhor.\\nCordeiro de Deus, que tirais os pecados do mundo, tende piedade de nós.\\n\\nV. Rogai por nós, Santa Mãe de Deus.\\nR. Para que sejamos dignos das promessas de Cristo. Amém."
                },
                {
                    id: "p_21",
                    title: "Ladainha do Sagrado Coração de Jesus",
                    category: "Ladainhas",
                    text: "Senhor, tende piedade de nós.\\nCristo, tende piedade de nós.\\nSenhor, tende piedade de nós.\\nJesus Cristo, ouvi-nos.\\nJesus Cristo, atendei-nos.\\n\\nDeus Pai dos céus, tende piedade de nós.\\nDeus Filho, Redentor do mundo, tende piedade de nós.\\nDeus Espírito Santo, tende piedade de nós.\\nSantíssima Trindade, que sois um só Deus, tende piedade de nós.\\n\\nCoração de Jesus, Filho do Pai Eterno, tende piedade de nós.\\nCoração de Jesus, formado pelo Espírito Santo no seio da Virgem Mãe,\\nCoração de Jesus, unido substancialmente ao Verbo de Deus,\\nCoração de Jesus, de majestade infinita,\\nCoração de Jesus, templo santo de Deus,\\nCoração de Jesus, tabernáculo do Altíssimo,\\nCoração de Jesus, casa de Deus e porta do céu,\\nCoração de Jesus, fornalha ardente de caridade,\\nCoração de Jesus, santuário de justiça e de amor,\\nCoração de Jesus, cheio de bondade e de amor,\\nCoração de Jesus, abismo de todas as virtudes,\\nCoração de Jesus, digníssimo de todo o louvor,\\nCoração de Jesus, Rei e centro de todos os corações,\\nCoração de Jesus, no qual estão todos os tesouros da sabedoria e ciência,\\nCoração de Jesus, no qual habita toda a plenitude da divindade,\\nCoração de Jesus, no qual o Pai pôs as suas complacências,\\nCoração de Jesus, de cuja plenitude todos nós recebemos,\\nCoração de Jesus, desejado das colinas eternas,\\nCoração de Jesus, paciente e de muita misericórdia,\\nCoração de Jesus, rico para todos os que vos invocam,\\nCoração de Jesus, fonte de vida e de santidade,\\nCoração de Jesus, propiciação pelos nossos pecados,\\nCoração de Jesus, saciado de opróbrios,\\nCoração de Jesus, esmagado de dor por causa dos nossos crimes,\\nCoração de Jesus, obediente até à morte,\\nCoração de Jesus, transpassado pela lança,\\nCoração de Jesus, fonte de toda a consolação,\\nCoração de Jesus, nossa vida e ressurreição,\\nCoração de Jesus, nossa paz e reconciliação,\\nCoração de Jesus, vítima dos pecadores,\\nCoração de Jesus, salvação dos que em vós esperam,\\nCoração de Jesus, esperança dos que morrem em vós,\\nCoração de Jesus, delícia de todos os santos,\\n\\nCordeiro de Deus, que tirais os pecados do mundo, perdoai-nos, Senhor.\\nCordeiro de Deus, que tirais os pecados do mundo, ouvi-nos, Senhor.\\nCordeiro de Deus, que tirais os pecados do mundo, tende piedade de nós.\\n\\nV. Jesus, manso e humilde de coração.\\nR. Fazei o nosso coração semelhante ao vosso. Amém."
                },
                {
                    id: "p_22",
                    title: "Ladainha de São José",
                    category: "Ladainhas",
                    text: "Senhor, tende piedade de nós.\\nCristo, tende piedade de nós.\\nSenhor, tende piedade de nós.\\nCristo, ouvi-nos.\\nCristo, atendei-nos.\\n\\nDeus Pai dos céus, tende piedade de nós.\\nDeus Filho, Redentor do mundo, tende piedade de nós.\\nDeus Espírito Santo, tende piedade de nós.\\nSantíssima Trindade, que sois um só Deus, tende piedade de nós.\\n\\nSanta Maria, rogai por nós.\\nSão José, rogai por nós.\\nIlustre filho de Davi, rogai por nós.\\nLuz dos Patriarcas, rogai por nós.\\nEsposo da Mãe de Deus, rogai por nós.\\nCasto guarda da Virgem, rogai por nós.\\nSustentador do Filho de Deus, rogai por nós.\\nZeloso defensor de Cristo, rogai por nós.\\nChefe da Sagrada Família, rogai por nós.\\nJosé justíssimo, rogai por nós.\\nJosé castíssimo, rogai por nós.\\nJosé prudentíssimo, rogai por nós.\\nJosé fortíssimo, rogai por nós.\\nJosé obedientíssimo, rogai por nós.\\nJosé fidelíssimo, rogai por nós.\\nEspelho de paciência, rogai por nós.\\nAmante da pobreza, rogai por nós.\\nModelo dos operários, rogai por nós.\\nGlória da vida doméstica, rogai por nós.\\nGuarda das virgens, rogai por nós.\\nSustentáculo das famílias, rogai por nós.\\nConsolo dos desgraçados, rogai por nós.\\nEsperança dos doentes, rogai por nós.\\nPadroeiro dos moribundos, rogai por nós.\\nTerror dos demônios, rogai por nós.\\nProtetor da Santa Igreja, rogai por nós.\\n\\nCordeiro de Deus, que tirais os pecados do mundo, perdoai-nos, Senhor.\\nCordeiro de Deus, que tirais os pecados do mundo, ouvi-nos, Senhor.\\nCordeiro de Deus, que tirais os pecados do mundo, tende piedade de nós.\\n\\nV. Ele o constituiu senhor de sua casa.\\nR. E príncipe de todos os seus bens. Amém."
                },
                {
                    id: "p_23",
                    title: "Oração a São Miguel Arcanjo (Papa Leão XIII)",
                    category: "Santos",
                    text: "São Miguel Arcanjo, defendei-nos no combate;\\nsede o nosso refúgio contra as maldades e ciladas do demônio.\\n\\nOrdene-lhe Deus, instantemente o pedimos;\\ne vós, príncipe da milícia celeste,\\npelo poder divino, precipitai no inferno a Satanás\\ne a todos os espíritos malignos\\nque andam pelo mundo para perder as almas.\\n\\nAmém."
                },
                {
                    id: "p_24",
                    title: "Oração da Medalha de São Bento",
                    category: "Santos",
                    text: "A Cruz Sagrada seja a minha luz,\\nnão seja o dragão o meu guia.\\n\\nRetira-te, satanás!\\nNunca me aconselhes coisas vãs.\\nÉ mau o que tu me ofereces,\\nbebe tu mesmo o teu veneno!\\n\\n(Em latim)\\nCrux Sacra Sit Mihi Lux,\\nNon Draco Sit Mihi Dux.\\nVade Retro Satana!\\nNunquam Suade Mihi Vana.\\nSunt Mala Quae Libas,\\nIpse Venena Bibas.\\n\\nEm nome do Pai, do Filho e do Espírito Santo. Amém."
                },
                {
                    id: "p_25",
                    title: "Consagração a Nossa Senhora",
                    category: "Maria",
                    text: "Ó minha Senhora, ó minha Mãe,\\neu me ofereço todo a vós,\\ne em prova da minha devoção para convosco,\\nvos consagro neste dia\\nos meus olhos, os meus ouvidos,\\na minha boca, o meu coração\\ne inteiramente todo o meu ser.\\n\\nE porque assim sou vosso, ó incomparável Mãe,\\nguardai-me e defendei-me\\ncomo coisa e propriedade vossa.\\n\\nAmém."
                },
                {
                    id: "p_26",
                    title: "Atos das Virtudes Teologais (Fé, Esperança e Caridade)",
                    category: "Fundamentais",
                    text: "ATO DE FÉ:\\nMeu Deus, eu creio firmemente em tudo o que revelastes e que a Santa Igreja Católica nos ensina para crer, porque Vós sois a suma Verdade, que não podeis enganar-Vos nem enganar-nos. Neste sentimento quero viver e morrer.\\n\\nATO DE ESPERANÇA:\\nMeu Deus, eu espero com firme confiança que, pelos merecimentos de Nosso Senhor Jesus Cristo, me dareis a salvação eterna e as graças necessárias para alcançá-la, porque Vós, sumamente bom e fiel, o prometestes.\\n\\nATO DE CARIDADE:\\nMeu Deus, eu Vos amo de todo o meu coração e sobre todas as coisas, porque sois infinitamente bom e amável; e por amor de Vós amo ao meu próximo como a mim mesmo, perdoando de coração todas as injúrias recebidas. Senhor, aumentai a minha caridade! Amém."
                },
                {
                    id: "p_27",
                    title: "Te Deum (Hino Litúrgico de Ação de Graças)",
                    category: "Grandes Devoções",
                    text: "A Vós, ó Deus, louvamos; a Vós, Senhor, cantamos.\\nA Vós, Eterno Pai, adora toda a terra.\\nA Vós os Anjos, os Céus e todas as Potestades;\\na Vós os Querubins e Serafins proclamam sem cessar:\\n\\nSanto, Santo, Santo, Senhor Deus dos Exércitos!\\nCheios estão os céus e a terra da majestade da Vossa glória!\\n\\nA Vós o glorioso coro dos Apóstolos,\\na Vós a falange venerável dos Profetas,\\na Vós o exército brilhante dos Mártires louvam.\\n\\nPor toda a terra a Santa Igreja proclama o Vosso Nome:\\nPai de imensa majestade;\\nadorável, verdadeiro e único Filho;\\ne o Espírito Santo Paráclito.\\n\\nVós sois o Rei da Glória, ó Cristo!\\nVós sois o Filho eterno do Pai!\\nVós, para salvar o homem, não recusastes o seio da Virgem.\\nVós, vencendo o aguilhão da morte, abristes aos fiéis o Reino dos Céus.\\n\\nSalvai, Senhor, o Vosso povo e abençoai a Vossa herança!\\nGovernai-nos e exaltai-nos pela eternidade.\\nDia a dia Vos bendizemos e louvamos o Vosso Nome para sempre.\\nDignai-Vos, Senhor, neste dia, guardar-nos do pecado.\\nTende piedade de nós, Senhor, tende piedade de nós.\\nDesça sobre nós a Vossa misericórdia, como em Vós esperamos.\\nEm Vós, Senhor, esperei: não serei confundido eternamente. Amém."
                },
                {
                    id: "p_28",
                    title: "Tantum Ergo (Tão Sublime Sacramento / Bênção Eucarística)",
                    category: "Eucaristia",
                    text: "Tão sublime Sacramento\\nadoremos neste altar,\\npois o Antigo Testamento\\ndeu ao Novo seu lugar.\\nVenha a fé por suplemento\\nos sentidos completar.\\n\\nAo Eterno Pai cantemos\\ne a Jesus, o Salvador,\\nao Espírito exaltemos,\\nna Trindade eterno amor.\\nAo Deus Uno e Trino demos\\na glória, o louvor e o poder.\\nAmém.\\n\\nV. Do Céu lhes destes o pão.\\nR. Que contém em si todo o sabor.\\n\\nOREMOS:\\nSenhor Jesus Cristo, que neste admirável Sacramento nos deixastes o memorial da Vossa Paixão, dai-nos venerar de tal modo os sagrados mistérios do Vosso Corpo e Sangue, que sintamos continuamente em nós o fruto da Vossa Redenção. Vós que sois Deus com o Pai, na unidade do Espírito Santo. Amém."
                }`;

const oldTarget = `                { id: "p_15", title: "Oração da Noite (Exame de Consciência)", category: "Dia a dia", text: "Senhor, ao terminar este dia, venho à vossa presença.\\n\\n1. Ação de graças: Revejo o dia e agradeço pelos dons recebidos — a vida, os encontros, o pão, o trabalho.\\n\\n2. Luz do Espírito: Peço ao Espírito Santo que ilumine minha memória e meu coração.\\n\\n3. Revisão do dia: Onde estive hoje? O que fiz? Como amei? Onde faltei com o amor a Deus e ao próximo?\\n\\n4. Arrependimento: Peço perdão pelas faltas cometidas, pelas omissões do bem e pelas palavras que feriram.\\n\\n5. Propósito: Confio o amanhã à vossa providência e proponho amar melhor.\\n\\nGuardai-me nesta noite, Senhor, sob as vossas asas.\\nAmém." }`;

if (html.includes(oldTarget)) {
  html = html.replace(oldTarget, newPrayersSnippet);
  
  // Atualizar categorias
  html = html.replace(
    'categories: ["Fundamentais", "Maria", "Espírito Santo", "Eucaristia", "Confissão", "Misericórdia", "Santos", "Dia a dia"],',
    'categories: ["Fundamentais", "Maria", "Grandes Devoções", "Espírito Santo", "Eucaristia", "Confissão", "Misericórdia", "Santos", "Ladainhas", "Dia a dia"],'
  );
  
  fs.writeFileSync(indexPath, html, 'utf8');
  console.log('✓ index.html atualizado com sucesso com 28 orações canônicas e novas categorias de devoção!');
} else {
  console.error('! Alvo p_15 não encontrado no index.html');
}
